### ISSUE TITLE
Write scxa->cxg h5ad converter - obs only

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/scxa_2_cxg#1]
CxG Standard - latest approved version: https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md

Example h5ad file on scxa FTP: https://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/sc_experiments/E-CURD-2/

Attempt at mapping obs between schemas here: https://github.com/VirtualFlyBrain/scxa-to-h5ad/issues/1#issue-1881521372

It is also worth checking vars for compliance (making sure gene name. ID and type are stored in a schema compliant way.

Finally - `obsm` stored embeddings.  Ideally this would be compliant too.

**Comment by anitacaron** [comment]
It's missing [assay_ontology_term_id](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#assay_ontology_term_id). I didn't find yet a mapping for this.
