### ISSUE TITLE
Write runner script to convert scxa files to cxg h5ad and rdf

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/scxa_2_cxg#12]
- [x] runs conversion all scxa files to cxg h5ad
- [x] runs Pandasaurus on all files to generate rdf to load into OBASK
- [x] runs robot template pipeline to glue content together.

**Comment by dosumis** [comment]
@ubyndr has written a pipeline to run this for our KG.  We should be able to re-use this pipeline with relatively minimal adaption.

@ubyndr  - I haven't had a chance to look yet.  I'm assuming makefile + robot with curated tables as input => resolution to CxG files.  
For SCXA 
Curation for CxG = curation of author cell type label fields.  Not sure we need that for SCXA.

**Comment by ubyndr** [comment]
I have shared the scripts I wrote with Anita and explained what she needs to do.

**Comment by anitacaron** [comment]
It would be good to discuss about the author cell type label in the meeting today.

**Comment by anitacaron** [comment]
All done in the two linked PRs.
