### ISSUE TITLE
update CxG converter to support test mode - converting single file

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/scxa_2_cxg#14]
Needed to make testing more tractable

**Comment by anitacaron** [comment]
It's already possible to do it, just need to pass the full experiment name, for instance, "E-CURD-2"

**Comment by dosumis** [comment]
OK.  Can you write some doc?

**Comment by anitacaron** [comment]
I updated the [README](https://github.com/EBISPOT/scxa_2_cxg/blob/main/README.md)
