### ISSUE TITLE
Set up OBASK instance with basic config

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/scxa_2_cxg#6]
- [x] Set this up on a new repo - seeded using the templating mechanism in OBASK.
- [x] Configure with: 
   - composite metazoan from Uberon (includes CL, Uberon, FBbt and others - need to check if this includes stage ontologies and add if not)
   - Slice of EFO needed for assays - this should be conservative: perhaps terms used + some small number of grouping terms will be sufficient? Use https://robot.obolibrary.org/extract#mireot.  Suggested grouping terms - 'single cell library construction' + 'single cell RNA sequencing'.  Or we might just take everything under those 2 terms a check if sufficient?
    - Assess term usage to see what else is missing?

**Comment by anitacaron** [comment]
>  Set this up on a new repo - seeded using the templating mechanism in OBASK.

https://github.com/EBISPOT/scxa_kg

> composite metazoan from Uberon

https://github.com/EBISPOT/scxa_kg/blob/main/config/collectdata/vfb_fullontologies.txt

**Comment by anitacaron** [comment]
> Slice of EFO needed for assays

Following the curation documentation (image below), only terms under [single cell library construction](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0010183) are used, I created an EFO slice with everything under this class.

<img width="528" alt="Screenshot 2024-04-19 at 15 38 16" src="https://github.com/EBISPOT/scxa_2_cxg/assets/2208124/64671254-ffa6-4b91-8118-5f6f3ac0c7d5">

https://github.com/EBISPOT/scxa_2_cxg/blob/main/efo_slice.owl

And added to the OBASK configuration:

https://github.com/EBISPOT/scxa_kg/blob/main/config/collectdata/vfb_fullontologies.txt

**Comment by anitacaron** [comment]
After closing the issue https://github.com/EBISPOT/scxa_kg/issues/1, here can be closed.

**Comment by anitacaron** [comment]
OBASK instance is available to run locally in the repository https://github.com/EBISPOT/scxa_kg
