### ISSUE TITLE
Extend CxG conversion to cover - `var` (genes),

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/scxa_2_cxg#7]

**Comment by anitacaron** [comment]
The CxG scheme, only defines 5 columns: feature_is_filtered, feature_biotype, feature_length, feature_name and feature_reference
I've checked the columns available in the `var` in SCXA:
- type = feature_biotype
- gene_name = feature_name

In the CxG schema, the feature_name should be the Ensembl name. However, in some scxa experiments, there are Ensembl, Ensembl Havana, Havana, and RefSeq values, for instance, 'AC242953.1', 'Mt-nd1', 'Mt-nd2', 'Mt-co1', 'AABR07000398.1', etc. Should I remove the rows that are not Ensembl?

I didn't find other mappings.

**Comment by anitacaron** [comment]
cc @dosumis

**Comment by anitacaron** [comment]
The only mandatory column is `feature_is_filtered`. I put false to all.

**Comment by dosumis** [comment]
My undertanding is that we should use Ensembl names and IDs.  Where available, can you set the index (ID) and name to Ensembl?

**Comment by anitacaron** [comment]
They're mixed in the rows. There isn't a column for each value. The index is most of ENSMUSG.
