### ISSUE TITLE
Extend CxG conversion to cover - `uns` (general metadata)

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/scxa_2_cxg#9]

**Comment by anitacaron** [comment]
It doesn't look like any data in `uns` is expected as in the schema.

These are the columns in `uns`:
'hvg', 'markers_louvain_resolution_0.1', 'markers_louvain_resolution_0.1_filtered', 'markers_louvain_resolution_0.3', 'markers_louvain_resolution_0.3_filtered', 'markers_louvain_resolution_0.5', 'markers_louvain_resolution_0.5_filtered', 'markers_louvain_resolution_0.7', 'markers_louvain_resolution_0.7_filtered', 'markers_louvain_resolution_1.0', 'markers_louvain_resolution_1.0_filtered', 'markers_louvain_resolution_2.0', 'markers_louvain_resolution_2.0_filtered', 'markers_louvain_resolution_3.0', 'markers_louvain_resolution_3.0_filtered', 'markers_louvain_resolution_4.0', 'markers_louvain_resolution_4.0_filtered', 'markers_louvain_resolution_5.0', 'markers_louvain_resolution_5.0_filtered', 'neighbors', 'pca', scrublet

**Comment by anitacaron** [comment]
Schema values: title, batch_condition, {column}_colors, default_embedding, X_approximate_distribution

**Comment by dosumis** [comment]
We may have to mine some of the other files for general metadata.

**Comment by anitacaron** [comment]
Only the title is required. Got this from the IDF file.

**Comment by anitacaron** [comment]
Add `default_embedding: "X_umap_neighbors_n_neighbors_20`

**Comment by dosumis** [comment]
Add dataset curie 

e.g. 
SCXA:E-CURD-2

This is sufficient for rolling links to dataset files in general on FTP, SCXG web site and the CxG standard h5ad file that we produce. 

TBD: Do we store this in uns or do we just make it the ID of DataSet?
Decision: Save as property in dataset object.
